### ISSUE TITLE
Escape curly braces inside code blocks?

### ISSUE THREAD

**Issue by TClark1011** [valentine195/obsidian-markdown-attributes#1]
It seems like curly braces used inside code braces are always interpreted as being attributes and get hidden in preview mode.

**Example:**
Source Mode: 
![image](https://user-images.githubusercontent.com/48699309/129463950-1284c4d7-0aa9-4c4f-9a91-d500d22b3435.png)

Preview Mode:
![image](https://user-images.githubusercontent.com/48699309/129463955-9f5fcd7e-e3b3-4dee-91ff-161ae79d03ee.png)

The same also occurs with inline code:
Source Mode: 
![image](https://user-images.githubusercontent.com/48699309/129463986-f79d3d53-27bc-4f4c-aec5-4bad16ae056c.png)

Preview Mode:
![image](https://user-images.githubusercontent.com/48699309/129463992-9b88f1a0-699d-422d-aea4-7048349dc0b8.png)

Is there any way to escape the curly brace character so that it can be used inside code?

**Comment by valentine195** [comment]
Easier to make it just not parse inside code blocks. Should be fixed in 1.0.1
