### ISSUE TITLE
Long (16 characters or more) {.divclass} Causes Obsidian to Freeze

### ISSUE THREAD

**Issue by sigrunixia** [valentine195/obsidian-markdown-attributes#16]
I reported this on TTRPG but will make a formal report after collecting even more data last night (and accidentally crashing my Obsidian making a Zotero template, oy).

**Describe the bug**
Long named {.named} of 16 characters or more will cause Obsidian to Freeze if in live-edit-preview mode. It will trigger whether or not the {.named} has an associated CSS or not.

**Markdown Source**
```
moo
{.dragonscript}

moos
{.dragonscript}

moooooo
{.espruarFont}

{.dragonscriptFont} - This one seems to Froze Obsidian consistently
{.dragonscript-Dad} - This one seems to Froze Obsidian consistently
{.jibberjabbergobbl} - This one Froze Obsidian
{.jabberwockylovessomehockey} - This one took 5-10 seconds to Freeze Obsidian
```

**How to Reproduce**
In live-edit-preview mode and in any note, type in a `{.divclass}` that has long a long name. I did determine the minimum character count to trigger the change from no-crash to crash (16).  The live preview, it will freeze and you will be unable to perform most actions from Obsidian even within the menu. It requires a force-quit. 

**Relevant Details**
- No errors present in the console.
- No CSS Snippets Enabled
- No Plugins Enabled except this One
- Default Theme
- It can sometimes take a few moments to freeze.. 5-10 seconds. If you navigate away in time, you can "escape" it. 
- If you disable the add-on, then type in the offensive class `{.dragonscriptFont}`, then re-enable the add-on, Obsidian will freeze in live-edit-preview mode. 
	- However, when you restart obsidian after a force quit, sometimes you can move about until you try to edit the offensive class, then it freezes again. I had inconsistent results with this. 
- MacOSX Monteray, if it Matters

**Comment by valentine195** [comment]
hi, this should be fixed in the latest release
