### ISSUE TITLE
Attributes not recognized on a callout ending in a code block

### ISSUE THREAD

**Issue by Jnosh** [valentine195/obsidian-markdown-attributes#20]
Attributes not recognized on a callout ending in a code block:

```
>This doesn't work:
>
>```
>Lorem ipsum dolor sit amet.
>```
{ .class }
```

Instead an empty paragraph with the given attributes is inserted at the end of the callout.

<img width="236" alt="p" src="https://user-images.githubusercontent.com/3801202/218341793-ce9fb467-0f5a-49bc-b5cf-ad02ea862c2c.png">

If there is any content after the code block, the attributes are correctly attached to the callout.

```
>But this does:
>
>```
>Lorem ipsum dolor sit amet.
>```
>... because of the content after the code block...
{ .class }
```

**Comment by sigrunixia** [comment]
Related to #19
