### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by JeppeKlitgaard** [valentine195/obsidian-markdown-attributes#4]
I would like for this plugin to also work for math blocks.

Test case:
```
$$
\sin{θ} = …
$$
{ .hidden }
```

This currently makes an empty `<p>` that has the class `hidden`.

**Comment by valentine195** [comment]
Does it work if you put it on the same line as the bottom $$ ? Not sure if it will or not, just a guess.

**Comment by JeppeKlitgaard** [comment]
That would invalidate the latex block, unfortunately :(

**Comment by valentine195** [comment]
Hey, sorry this took so long, but this should work in version 1.1.0.
