### ISSUE TITLE
please ignore when inside code block

### ISSUE THREAD

**Issue by rubaboo** [valentine195/obsidian-markdown-attributes#5]
**Describe the bug**
In preview mode, the code inside curly brackets is shown at the top of the code block.

**Markdown Source**

    ```powershell
    do {
    Start-Process "ms-settings:mousetouchpad"
    sleep 1
    get-process | where-object {$_.MainWindowTitle -eq "Settings"} | % { $_.CloseMainWindow() }
    sleep 2
    } while ($true)
    ```

**Screenshots**
![image](https://user-images.githubusercontent.com/212368/143575246-42a7c745-3919-4249-81f6-23585553b10c.png)

**Comment by valentine195** [comment]
Hey, sorry this took so long, but this should be fixed in version 1.1.0.
