### ISSUE TITLE
Only first Link found when using Multiple Internal Links 

### ISSUE THREAD

**Issue by HAJ523** [valentine195/obsidian-markdown-attributes#6]
**For example:**

[[pageA]]{.PFFF}  [[pageB]]{.PFFF}  [[pageC]]{.PFFF}

**Becomes in Preview Mode:**

Y Y{.PFFF} Y{.PFFF}

(Note that in the above example the first link is correctly getting its class applied.)

**Additional Considerations:**
 - No spaces between should still allow styling.
   - Source: [[pageA]]{.PFFF}[[pageB]]{.PFFF}[[pageC]]{.PFFF}
   - Results: pageApageBpageC (with formatting for each link different)
 - Consider if Link renaming will affect results.
   - Source: [[pageA|A]]{.PFFF}[[pageB|B]]{.PFFF}[[pageC|C]]{.PFFF}
   - Results: ABC (with formatting for each letter different.

**Comment by HAJ523** [comment]
**Potential Workaround**
When Possible: You can embed part of the formatting into your link/file name.
Note Text: [[TEST-6F6-0;0|.]]
The CSS: [href*="-6F6-"] {color: #6F6;}
Resulting Link is Light Green.

**Comment by Thylane** [comment]
It's simple to achieve what you want.

Just change your syntax, use `[[link{.class}]] ` instead of `[[link]]{.class}`.
In case of renaming, use `[[link|alias{.class}]]`.

For Example, `[111{.purple}]()  [222{.red}]()  [[Callout|Rename{.yellow}]]` will result in:

![image](https://user-images.githubusercontent.com/69613663/182141419-6df60938-7760-45af-903e-2b7b35a4b08c.png)

**Comment by sigrunixia** [comment]
@valentine195 Current documentation states for singular wikilinks it should be:
`[[Test 123]] { .wikilink}`

We currently have no documentation on multiple consecutive links. 

Whereas I am able to confirm the styling works by @Thylane for multiple.

If this is not a bug (or not a fixable bug), are you fine with me updating the documentation to always suggest including the class inside the link to bring consistency with this fix (and also markdown links which work similarly)?
