### ISSUE TITLE
Can't set attributes on block quote that contains nested list

### ISSUE THREAD

**Issue by lukePeavey** [valentine195/obsidian-markdown-attributes#8]
**Describe the bug**

It is not possible to set attributes on a block quote when it contains nested list elements.  I tried placing the attribute definition on the next line after the block quote, inside the block quote after a blank line, but neither of these worked. 

Possible duplicate of #7

**Markdown Source**

In this example, the class is applied to the `<blockquote>` as expected

```markdown
> Blockquote WITHOUT nested list (works)
> One
> Two 
> Three
{class="blue"}
```

In this example the class is applied to the list element

```markdown
> Blockquote WITH nested list (does not work)
> - One
> - Two 
> - Three
{class="blue"}
```

**Screenshots**

<img width="1133" alt="Screen Shot 2022-02-19 at 1 44 55 PM" src="https://user-images.githubusercontent.com/8286271/154814612-870bc93a-a58a-4399-a5ad-4bd0687b2f86.png">

**Workaround**

I did find a workaround... if you include the attribute inside the `blockquote`, with two blank lines and a `&nbsp;` after the list, the class is applied to the block quote. 

<img width="1133" alt="Screen Shot 2022-02-19 at 1 59 22 PM" src="https://user-images.githubusercontent.com/8286271/154815079-2e8cf953-5fad-4681-841f-e7a93d17b3b7.png">

**Comment by lukePeavey** [comment]
Great plugin BTW!

**Comment by sigrunixia** [comment]
@lukePeavey Do you happen to still have the CSS you used?

Using the CSS of:
```css
.blockquote-test {
    color: crimson;
    background-color: #00ff00;
    border: 1px solid #000000;
    border-radius: 1em;
    padding: 1em;
    margin: 1em;
    width: 50%;
    height: 50%;
    overflow: auto;
    box-shadow: 0.1em 0.1em 0.1em #000000;
}
```

I get this: 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/68425372/234344451-f1493784-eff4-47fb-be3d-b8c3cfc1e85f.png">


Obviously not all my CSS is working so we'll need to investigate that, but seeing what you were trying to apply would be helpful as well. 


---

However, @valentine195 I am also running into:

```js
plugin:markdown-attributes:90 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at _Processor.getAttrs (plugin:markdown-attributes:90:11)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:125:26)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
    at _Processor.recurseAndParseElements (plugin:markdown-attributes:136:31)
```

Two issues in. :)
