### ISSUE TITLE
Classes do not pass-through to Publish

### ISSUE THREAD

**Issue by mikebesso** [valentine195/obsidian-markdown-attributes#9]
This is AWESOME.  Great Job.  

I am now able to specify classes and ids to do some custom styling.

However, when I publish using Obsidian Publish, the custom classes do not make it to the published version.  Instead, 

 { .my-list }

appears on the page.

Is there any chance this can be made to work with Obsidian Publish?

If you need someone to test this change out, just let me know.

**Comment by valentine195** [comment]
Plugins do not currently work for publish, but I believe that is on the Obsidian roadmap.

If you have a custom domain there is a possibility that I could create a script when i have more time that you could load that would enable it, like I do for Admonitions.

**Comment by mikebesso** [comment]
Thanks for the quick response.  I'll look into a custom domain.
 
btw:  Admonitions are AWESOME.
